server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/paper_manager?serverTimezone=GMT&autoReconnect=true&useSSL=false&charset=UTF-8
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.zhang: debug

mybatis-plus:
  global-config:
    db-config:
      table-underline: false
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


  #分页插件设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql